name: Build Tachiyomi Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build APK
      run: |
        ./gradlew assembleDebug
        mkdir -p build/outputs/apk/
        cp app/build/outputs/apk/debug/app-debug.apk build/outputs/apk/zerobyw-ext-debug.apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: zerobyw-extension
        path: build/outputs/apk/zerobyw-ext-debug.apk
